import { FAQItemType } from '../types';

export const phoneFaqs: FAQItemType[] = [
  {
    id: 1,
    question: "What is a random phone number generator?",
    answer: "A random phone number generator is a tool that generates valid but random phone numbers for any country or area code. These numbers are formatted correctly but are not assigned to real users, making them ideal for testing, data validation, and educational purposes."
  },
  {
    id: 2,
    question: "How does the random phone number generator work?",
    answer: "Our random phone number generator uses predefined formats and country-specific rules to produce numbers that look real but are unassigned. Simply enter the country or area code you need, select the quantity, and click \"Generate Numbers.\""
  },
  {
    id: 3,
    question: "Why would I need a random phone number generator?",
    answer: [
      "A random phone number generator is useful for:",
      "Software testing and QA",
      "Creating placeholder data for forms",
      "Avoiding the use of real phone numbers in demos",
      "Generating test accounts for apps and websites"
    ]
  },
  {
    id: 4,
    question: "Are the generated phone numbers real?",
    answer: "No, the numbers generated by our random phone number generator are not real and not assigned to any individuals or businesses. They are formatted correctly but do not belong to active phone lines."
  },
  {
    id: 5,
    question: "Can I generate phone numbers for specific countries?",
    answer: "Yes! Our random phone number generator supports multiple countries, allowing you to specify the country or area code you need."
  },
  {
    id: 6,
    question: "Can I use these numbers for verification (OTP, SMS, or calls)?",
    answer: "No, since our random phone numbers are unassigned, they cannot receive SMS messages, calls, or verification codes."
  },
  {
    id: 7,
    question: "Can I generate bulk random phone numbers?",
    answer: "Yes! Our tool allows you to generate multiple phone numbers at once. Simply specify the quantity, and our random phone number generator will provide a list."
  },
  {
    id: 8,
    question: "Can I generate phone numbers with a specific area code?",
    answer: "Yes, you can input an area code, and our generator will create numbers that match your criteria."
  },
  {
    id: 9,
    question: "Can I export the generated numbers?",
    answer: "Yes! You can copy, download, or export the generated phone numbers for testing and development purposes."
  },
  {
    id: 10,
    question: "Is using a random phone number generator legal?",
    answer: "Yes! Using a random phone number generator is legal as long as you do not misuse the numbers. They are not real phone numbers, so they should not be used for fraud, spam, or misleading activities."
  },
  {
    id: 11,
    question: "Do you store the generated phone numbers?",
    answer: "No, we do not store any generated phone numbers. Every time you refresh or use the generator, a new set of numbers is created."
  },
  {
    id: 12,
    question: "Is this random phone number generator free?",
    answer: "Yes! Our random phone number generator is completely free to use for generating random numbers."
  },
  {
    id: 13,
    question: "Can I integrate the random phone number generator into my app?",
    answer: "We offer an API for developers who need to generate phone numbers programmatically. Contact us for integration details!"
  },
  {
    id: 14,
    question: "Does this tool support VoIP, landline, or mobile numbers?",
    answer: "Yes, our generator can create random phone numbers that resemble mobile, landline, or VoIP formats based on country-specific rules."
  }
]; 