export type NhieCategory = 'classic' | 'funny' | 'party' | 'couples' | 'kids';

export const categoryLabels: Record<NhieCategory, string> = {
  classic: 'Classic',
  funny: 'Funny',
  party: 'Party',
  couples: 'For couples',
  kids: 'For kids',
};

export const statements: Record<NhieCategory, string[]> = {
  classic: [
    'Never have I ever broken a bone.',
    'Never have I ever traveled to another country.',
    'Never have I ever gone camping.',
    'Never have I ever ridden a horse.',
    'Never have I ever met a celebrity.',
    'Never have I ever pulled an all-nighter.',
    'Never have I ever been on live TV or radio.',
    'Never have I ever forgotten someone’s name right after meeting them.',
    'Never have I ever gone a whole day without my phone.',
    'Never have I ever learned to play an instrument.',
    'Never have I ever cried during a movie.',
    'Never have I ever been skydiving or bungee jumping.',
    'Never have I ever gotten lost in a new city.',
    'Never have I ever won a trophy or medal.',
    'Never have I ever stayed up to watch the sunrise.',
  ],
  funny: [
    'Never have I ever walked into a glass door.',
    'Never have I ever laughed so hard that I snorted.',
    'Never have I ever waved back at someone who wasn’t waving at me.',
    'Never have I ever texted the wrong person something embarrassing.',
    'Never have I ever tripped in public and played it off.',
    'Never have I ever called a teacher “mom” or “dad” by accident.',
    'Never have I ever fallen asleep in a meeting or class.',
    'Never have I ever sung the wrong lyrics confidently for years.',
    'Never have I ever talked to myself and gotten caught.',
    'Never have I ever forgotten why I walked into a room.',
    'Never have I ever pushed a “pull” door.',
    'Never have I ever laughed at the wrong moment.',
    'Never have I ever pretended to know a song I had never heard.',
    'Never have I ever lost my phone while talking on it.',
  ],
  party: [
    'Never have I ever sung karaoke in front of strangers.',
    'Never have I ever danced on a table.',
    'Never have I ever stayed out until sunrise.',
    'Never have I ever gone to a concert alone.',
    'Never have I ever crashed a party I wasn’t invited to.',
    'Never have I ever lost a bet and had to do a dare.',
    'Never have I ever been the last one to leave a party.',
    'Never have I ever told a white lie to get out of plans.',
    'Never have I ever fallen asleep at a party.',
    'Never have I ever sent a risky text and immediately regretted it.',
    'Never have I ever gone on a spontaneous road trip.',
    'Never have I ever worn a costume when no one else dressed up.',
  ],
  couples: [
    'Never have I ever stalked a crush on social media.',
    'Never have I ever had a crush on a friend.',
    'Never have I ever written someone a love letter.',
    'Never have I ever gone on a blind date.',
    'Never have I ever been nervous on a first date.',
    'Never have I ever said “I love you” first.',
    'Never have I ever planned a surprise for my partner.',
    'Never have I ever re-read old messages from someone I liked.',
    'Never have I ever fallen for someone at first sight.',
    'Never have I ever kept a gift from an ex.',
    'Never have I ever danced in the rain with someone.',
    'Never have I ever made a playlist for a crush.',
  ],
  kids: [
    'Never have I ever eaten an entire pizza by myself.',
    'Never have I ever stayed up past midnight.',
    'Never have I ever pretended to be sick to skip school.',
    'Never have I ever built a blanket fort.',
    'Never have I ever made a funny face at a stranger.',
    'Never have I ever had ice cream for breakfast.',
    'Never have I ever lost a tooth eating something.',
    'Never have I ever been scared of the dark.',
    'Never have I ever beaten a grown-up at a video game.',
    'Never have I ever made a slime mess.',
    'Never have I ever sung into a hairbrush like a microphone.',
    'Never have I ever fallen off a bike.',
  ],
};
