import { Metadata } from 'next';
import { Mailbox, MapPin, Phone } from 'lucide-react';
import ContactForm from './ContactForm';


export const metadata: Metadata = {
  title: 'Contact Us | Random Generator Tools',
  description: "Get in touch with the team behind Random Generator Tools. We&apos;d love to hear from you!",
};

export default function ContactPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <div className="text-center space-y-4 mb-12">
        <h1 className="text-4xl font-bold tracking-tight">Contact Us</h1>
        <p className="text-xl text-muted-foreground">
          Have questions or feedback? We&apos;d love to hear from you!
        </p>
      </div>

      <div className="grid md:grid-cols-5 gap-12">
        <div className="md:col-span-2 space-y-8">
          <div>
            <h2 className="text-2xl font-semibold mb-4">Get In Touch</h2>
            <p className="text-muted-foreground mb-6">
              We&apos;re here to help and answer any questions you might have. 
              We look forward to hearing from you.
            </p>
          </div>

          <div className="space-y-4">
            <div className="flex items-start gap-4">
              <div className="bg-primary/10 p-3 rounded-full">
                <Mailbox className="h-6 w-6 text-primary" />
              </div>
              <div>
                <h3 className="font-medium">Email Us</h3>
                <a href="mailto:hello@randomyl.com" className="text-muted-foreground hover:text-primary">
                  hello@randomyl.com
                </a>
              </div>
            </div>

            <div className="flex items-start gap-4">
              <div className="bg-primary/10 p-3 rounded-full">
                <Phone className="h-6 w-6 text-primary" />
              </div>
              <div>
                <h3 className="font-medium">Call Us</h3>
                <p className="text-muted-foreground">+1 (435) 215-8000</p>
              </div>
            </div>

            <div className="flex items-start gap-4">
              <div className="bg-primary/10 p-3 rounded-full">
                <MapPin className="h-6 w-6 text-primary" />
              </div>
              <div>
                <h3 className="font-medium">Visit Us</h3>
                <p className="text-muted-foreground">
                  Randomyl<br />
                  Toronto, ON, Canada
                </p>
              </div>
            </div>
          </div>

          <div className="pt-6">
            <h3 className="text-lg font-medium mb-2">Follow Us</h3>
            <div className="flex gap-4">
              <a href="#" className="text-muted-foreground hover:text-primary">Twitter</a>
              <a href="#" className="text-muted-foreground hover:text-primary">GitHub</a>
              <a href="#" className="text-muted-foreground hover:text-primary">LinkedIn</a>
            </div>
          </div>
        </div>

        <div className="md:col-span-3">
          <div className="border rounded-lg p-6 bg-card">
            <h2 className="text-2xl font-semibold mb-6">Send us a message</h2>
            <ContactForm />
          </div>
        </div>
      </div>

      <div className="mt-16 space-y-8">
        <div className="border-t pt-8">
          <h2 className="text-2xl font-semibold mb-4">Frequently Asked Questions</h2>
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-medium">Are your tools free to use?</h3>
              <p className="text-muted-foreground">Yes, all of our generator tools are completely free to use.</p>
            </div>
            <div>
              <h3 className="text-lg font-medium">Can I use the generated content commercially?</h3>
              <p className="text-muted-foreground">
                Yes, you can use the content generated by our tools for commercial purposes. 
                However, please ensure you comply with any applicable laws and regulations.
              </p>
            </div>
            <div>
              <h3 className="text-lg font-medium">How do your random generators work?</h3>
              <p className="text-muted-foreground">
                We use a combination of algorithms and AI to generate random content. Our tools
                are designed to produce high-quality, contextually relevant results while maintaining
                true randomness.
              </p>
            </div>
            <div>
              <h3 className="text-lg font-medium">Can I suggest a new generator tool?</h3>
              <p className="text-muted-foreground">
                Absolutely! We&apos;re always looking to expand our collection of tools. 
                Use the contact form to send us your ideas.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 