export type TriviaCategory =
  | 'general' | 'geography' | 'history' | 'science' | 'movies' | 'music' | 'sports' | 'animals';

export const categoryLabels: Record<TriviaCategory, string> = {
  general: 'General knowledge',
  geography: 'Geography',
  history: 'History',
  science: 'Science & nature',
  movies: 'Movies & TV',
  music: 'Music',
  sports: 'Sports',
  animals: 'Animals',
};

export interface TriviaItem {
  q: string;
  a: string;
}

// Only well-established, verifiable facts. Keep answers short and unambiguous.
export const trivia: Record<TriviaCategory, TriviaItem[]> = {
  general: [
    { q: 'How many continents are there on Earth?', a: 'Seven' },
    { q: 'What is the largest planet in our solar system?', a: 'Jupiter' },
    { q: 'How many sides does a hexagon have?', a: 'Six' },
    { q: 'What is the chemical symbol for gold?', a: 'Au' },
    { q: 'How many colors are in a rainbow?', a: 'Seven' },
    { q: 'What is the most widely spoken language in the world by native speakers?', a: 'Mandarin Chinese' },
    { q: 'How many minutes are in a full day?', a: '1,440' },
    { q: 'What is the hardest natural substance on Earth?', a: 'Diamond' },
    { q: 'How many strings does a standard guitar have?', a: 'Six' },
    { q: 'What is the smallest prime number?', a: 'Two' },
    { q: 'What does "www" stand for?', a: 'World Wide Web' },
    { q: 'How many sides does a stop sign have?', a: 'Eight' },
  ],
  geography: [
    { q: 'What is the capital of France?', a: 'Paris' },
    { q: 'What is the capital of Japan?', a: 'Tokyo' },
    { q: 'What is the longest river in the world?', a: 'The Nile (by most measures)' },
    { q: 'Which is the largest country in the world by area?', a: 'Russia' },
    { q: 'What is the smallest country in the world?', a: 'Vatican City' },
    { q: 'On which continent is the Sahara Desert?', a: 'Africa' },
    { q: 'What is the tallest mountain above sea level?', a: 'Mount Everest' },
    { q: 'Which ocean is the largest?', a: 'The Pacific Ocean' },
    { q: 'What is the capital of Australia?', a: 'Canberra' },
    { q: 'Which country has the most people?', a: 'India' },
    { q: 'What is the capital of Canada?', a: 'Ottawa' },
    { q: 'Which U.S. state is the largest by area?', a: 'Alaska' },
  ],
  history: [
    { q: 'In what year did World War II end?', a: '1945' },
    { q: 'Who was the first President of the United States?', a: 'George Washington' },
    { q: 'Which ancient civilization built the pyramids of Giza?', a: 'The ancient Egyptians' },
    { q: 'In what year did the Titanic sink?', a: '1912' },
    { q: 'Who painted the Mona Lisa?', a: 'Leonardo da Vinci' },
    { q: 'The Great Wall is located in which country?', a: 'China' },
    { q: 'Who was the first person to walk on the Moon?', a: 'Neil Armstrong' },
    { q: 'In what year did the Berlin Wall fall?', a: '1989' },
    { q: 'Which country gifted the Statue of Liberty to the United States?', a: 'France' },
    { q: 'Who wrote the play "Romeo and Juliet"?', a: 'William Shakespeare' },
    { q: 'What was the name of the ship the Pilgrims sailed on to America in 1620?', a: 'The Mayflower' },
  ],
  science: [
    { q: 'What planet is known as the Red Planet?', a: 'Mars' },
    { q: 'What gas do plants absorb from the air for photosynthesis?', a: 'Carbon dioxide' },
    { q: 'What is the chemical symbol for water?', a: 'H₂O' },
    { q: 'How many bones are in the adult human body?', a: '206' },
    { q: 'What is the closest star to Earth?', a: 'The Sun' },
    { q: 'What is the powerhouse of the cell?', a: 'The mitochondria' },
    { q: 'What force keeps us on the ground?', a: 'Gravity' },
    { q: 'What is the largest organ in the human body?', a: 'The skin' },
    { q: 'At what temperature does water freeze in Celsius?', a: '0 degrees' },
    { q: 'What is the speed of light approximately?', a: 'About 300,000 km per second' },
    { q: 'Which blood type is known as the universal donor?', a: 'O negative' },
  ],
  movies: [
    { q: 'In "The Wizard of Oz," what color are Dorothy\'s slippers (in the film)?', a: 'Ruby red' },
    { q: 'What is the name of the toy cowboy in "Toy Story"?', a: 'Woody' },
    { q: 'Which film features a shark terrorizing a beach town?', a: 'Jaws' },
    { q: 'What is the highest-grossing film franchise based on a wizard boy?', a: 'Harry Potter' },
    { q: 'In "Star Wars," who is Luke Skywalker\'s father?', a: 'Darth Vader' },
    { q: 'What animated movie features a snowman named Olaf?', a: 'Frozen' },
    { q: 'Who directed "Jurassic Park" (1993)?', a: 'Steven Spielberg' },
    { q: 'In "The Lion King," what is the name of the lion cub?', a: 'Simba' },
    { q: 'What is the name of the fictional African nation in "Black Panther"?', a: 'Wakanda' },
    { q: 'In "Finding Nemo," what kind of fish is Nemo?', a: 'A clownfish' },
  ],
  music: [
    { q: 'How many keys are on a standard piano?', a: '88' },
    { q: 'Which band performed "Hey Jude"?', a: 'The Beatles' },
    { q: 'How many strings does a violin have?', a: 'Four' },
    { q: 'What instrument has 47 strings and is played with the fingers?', a: 'The harp' },
    { q: 'Which singer is known as the "King of Pop"?', a: 'Michael Jackson' },
    { q: 'What is the highest female singing voice?', a: 'Soprano' },
    { q: 'How many notes are in a standard musical octave (inclusive)?', a: 'Eight' },
    { q: 'Which classical composer was deaf for much of his later life?', a: 'Ludwig van Beethoven' },
    { q: 'What family of instruments does the trumpet belong to?', a: 'Brass' },
    { q: 'Which music streaming app is known for its green logo?', a: 'Spotify' },
  ],
  sports: [
    { q: 'How many players are on a standard soccer team on the field?', a: 'Eleven' },
    { q: 'In which sport would you perform a slam dunk?', a: 'Basketball' },
    { q: 'How often are the Summer Olympic Games held?', a: 'Every four years' },
    { q: 'How many points is a touchdown worth in American football?', a: 'Six' },
    { q: 'In tennis, what is a score of zero called?', a: 'Love' },
    { q: 'How many holes are played in a full round of golf?', a: 'Eighteen' },
    { q: 'Which country has won the most FIFA World Cup titles?', a: 'Brazil' },
    { q: 'In baseball, how many strikes make an out?', a: 'Three' },
    { q: 'What sport is known as "the king of sports" globally?', a: 'Soccer (football)' },
    { q: 'How many rings are on the Olympic flag?', a: 'Five' },
  ],
  animals: [
    { q: 'What is the largest animal on Earth?', a: 'The blue whale' },
    { q: 'What is the fastest land animal?', a: 'The cheetah' },
    { q: 'How many legs does a spider have?', a: 'Eight' },
    { q: 'What is the tallest animal in the world?', a: 'The giraffe' },
    { q: 'Which bird is known for its ability to mimic human speech?', a: 'The parrot' },
    { q: 'What do you call a group of lions?', a: 'A pride' },
    { q: 'Which mammal is known to lay eggs?', a: 'The platypus (and the echidna)' },
    { q: 'What is the only mammal capable of true flight?', a: 'The bat' },
    { q: 'How many hearts does an octopus have?', a: 'Three' },
    { q: 'What is a baby kangaroo called?', a: 'A joey' },
  ],
};
