// Verified, evergreen facts sourced via Perplexity (sonar, grounded) and human-reviewed 2026-06-09.
// Client-side data — the generator serves these instantly with no runtime API call.

export type FactCategory = 'science' | 'space' | 'animals' | 'history' | 'humanBody' | 'geography' | 'food';

export const facts: Record<FactCategory, string[]> = {
  science: [
    'Light travels from the Sun to Earth in about eight minutes.',
    'Water can exist as a solid, liquid, and gas on Earth.',
    'Bananas are berries, but strawberries are not.',
    'The human stomach lining replaces itself regularly to protect the body from digestive acid.',
    'Venus spins in the opposite direction from most planets.',
    'The Moon is slowly moving away from Earth.',
    'Earth’s rotation is gradually slowing over time.',
    'Identical twins do not have identical fingerprints.',
    'A day on Mercury is longer than its year.',
    'A cloud is made of tiny water droplets or ice crystals, not water vapor alone.',
    'Sound travels faster through water than through air.',
    'Most of the oxygen you breathe is produced by ocean photosynthetic organisms.',
  ],
  space: [
    'The Sun contains most of the mass in the solar system.',
    'A year on Venus is shorter than a day on Venus.',
    'Mercury has no substantial atmosphere to trap heat well.',
    'Mars has the largest volcano in the solar system, Olympus Mons.',
    'The Moon always shows nearly the same face to Earth.',
    'There are more stars in the universe than grains of sand on Earth.',
    'A black hole’s gravity can be so strong that even light cannot escape.',
    'The International Space Station travels around Earth roughly every 90 minutes.',
    'Pluto was reclassified as a dwarf planet in 2006.',
    'Saturn is less dense than water.',
    'One Earth could fit across the Sun many times.',
    'The asteroid belt lies between Mars and Jupiter.',
  ],
  animals: [
    'Octopuses have three hearts.',
    'Honeybees communicate the direction of food with a waggle dance.',
    'A group of flamingos is called a flamboyance.',
    'Dolphins are mammals, not fish.',
    'Penguins are birds that cannot fly.',
    'Bats are the only mammals capable of true flight.',
    'A giraffe has the same number of neck vertebrae as a human.',
    'Sharks have been on Earth far longer than trees.',
    'An ostrich egg is the largest egg of any living bird.',
    'Some turtles can breathe through their rear ends.',
    'Cows have a four-chambered stomach.',
    'Sea otters use tools to open shellfish.',
  ],
  history: [
    'The Great Wall of China was built over many centuries by different dynasties.',
    'The pyramids of Giza are among the oldest surviving wonders of the ancient world.',
    'The printing press helped make books much more widely available.',
    'Ancient Romans used concrete in construction.',
    'The wheel was invented thousands of years ago.',
    'The Rosetta Stone helped scholars understand Egyptian hieroglyphs.',
    'The first successful powered airplane flight happened in 1903.',
    'The Library of Alexandria is famous for its historical importance and later loss.',
    'The lunar landing of 1969 was watched around the world.',
    'The Eiffel Tower was once considered temporary.',
    'The Silk Road connected Asia, Africa, and Europe through trade.',
    'The Titanic sank after striking an iceberg in 1912.',
  ],
  humanBody: [
    'The human body has 206 bones in adulthood.',
    'Babies are born with more bones than adults.',
    'The heart is a muscle that pumps blood continuously.',
    'The brain uses a large share of the body’s energy.',
    'Skin is the body’s largest organ.',
    'The left lung is smaller than the right lung to make room for the heart.',
    'Taste buds help detect flavors dissolved in saliva.',
    'Hair and nails are made mostly of keratin.',
    'The small intestine is much longer than the large intestine.',
    'Red blood cells carry oxygen through the body.',
    'Human fingerprints are unique to each person.',
    'The body constantly replaces old cells with new ones.',
  ],
  geography: [
    'Mount Everest is the highest mountain above sea level.',
    'The Dead Sea is one of the saltiest bodies of water on Earth.',
    'The Nile is traditionally described as one of the longest rivers in the world.',
    'The Sahara is the largest hot desert.',
    'Antarctica is the coldest continent.',
    'The Equator divides Earth into the Northern and Southern Hemispheres.',
    'Australia is both a country and a continent.',
    'Greenland is mostly covered by ice.',
    'The Amazon River basin contains the world’s largest tropical rainforest.',
    'Hawaii formed from volcanic activity over a hotspot.',
    'The Pacific Ocean is the largest ocean on Earth.',
    'The Mariana Trench is the deepest known ocean trench.',
  ],
  food: [
    'Honey can remain edible for a very long time if kept dry and sealed.',
    'Chocolate comes from cacao beans.',
    'Potatoes are tubers, not roots.',
    'Tomatoes are fruits botanically, though often used as vegetables.',
    'Apples float in water because they contain a lot of air.',
    'Vanilla flavor originally comes from an orchid.',
    'Cheese is made by coagulating milk proteins.',
    'Yogurt is made using bacterial fermentation.',
    'Most table salt is the mineral halite.',
    'Cinnamon comes from the inner bark of trees.',
    'Rice is a staple food for much of the world.',
    'Peanuts grow underground, unlike many other nuts.',
  ],
};

export const categoryLabels: Record<FactCategory, string> = {
  science: 'Science',
  space: 'Space',
  animals: 'Animals',
  history: 'History',
  humanBody: 'Human body',
  geography: 'Geography',
  food: 'Food',
};
