export type QuestionCategory = 'icebreakers' | 'fun' | 'deep' | 'wouldYouRather';

export const questions: Record<QuestionCategory, string[]> = {
  icebreakers: [
    'What is your favorite way to spend a weekend?',
    'If you could have any animal as a pet, what would you choose?',
    'What is a hobby you have always wanted to try?',
    'What is your favorite season and why?',
    'What is the best meal you have ever had?',
    'If you could visit any country, where would you go first?',
    'What is your go-to song to sing along with?',
    'What is something small that always makes you smile?',
    'What is your favorite movie to watch again and again?',
    'If you could learn any language instantly, which would it be?',
    'What is the best gift you have ever received?',
    'What is your favorite thing about where you live?',
    'What is a book that you would recommend to anyone?',
    'What is your favorite holiday tradition?',
    'If you could meet any historical figure, who would it be?',
    'What is the most interesting place you have ever visited?',
    'What is your favorite kind of weather?',
    'What is a skill you are proud of having?',
    'What is your favorite dessert of all time?',
    'If you could have dinner with anyone, who would it be?',
    'What is the best advice you have ever been given?',
    'What is your favorite way to relax after a long day?',
    'What is a sport or game you love to play?',
    'What is your favorite thing to do outdoors?',
  ],
  fun: [
    'If you could be invisible for a day, what would you do?',
    'What superpower would you most want to have?',
    'If animals could talk, which one would be the rudest?',
    'What would be the title of your autobiography?',
    'If you could only eat one food forever, what would it be?',
    'What is the silliest thing you are afraid of?',
    'If you were a flavor of ice cream, what would you be?',
    'What would you do if you won the lottery tomorrow?',
    'If you could swap lives with anyone for a day, who would it be?',
    'What is the strangest dream you can remember?',
    'If you could rename a color, what would you call it?',
    'What is the most useless talent you have?',
    'If you had a robot, what would you ask it to do first?',
    'What would your dream treehouse look like?',
    'If you could time travel, would you go to the past or the future?',
    'What is the funniest word in any language you know?',
    'If you could turn any activity into an Olympic sport, what would you win a medal for?',
    'What would you name a boat if you owned one?',
    'If you could live in any cartoon world, which would you pick?',
    'What is the best costume you have ever worn?',
    'If you could have a theme song that played when you walked in, what would it be?',
    'What is the weirdest food combination you secretly enjoy?',
    'If you could be any age forever, what age would you choose?',
    'What imaginary creature do you wish were real?',
  ],
  deep: [
    'What does a perfect day look like to you?',
    'What is something you have changed your mind about recently?',
    'What are you most grateful for right now?',
    'What does success mean to you?',
    'What is a lesson you learned the hard way?',
    'What makes you feel truly at peace?',
    'What is something you wish more people understood about you?',
    'What is a memory you hope you never forget?',
    'What do you think makes a friendship last?',
    'What is one thing you would tell your younger self?',
    'What is a goal you are quietly working toward?',
    'What is something that always inspires you?',
    'How do you like to show people that you care?',
    'What does kindness look like to you?',
    'What is a challenge that helped you grow?',
    'What do you value most in the people around you?',
    'What is something you are proud of that few people know about?',
    'What helps you feel brave when you are nervous?',
    'What is a tradition or value you want to carry forward?',
    'What does it mean to you to live a good life?',
    'What is a question you wish people asked you more often?',
    'What is something you are curious to learn more about?',
    'What is a moment when you felt truly proud of yourself?',
    'What do you hope people remember about you?',
  ],
  wouldYouRather: [
    'Would you rather be able to fly or be able to breathe underwater?',
    'Would you rather have unlimited books or unlimited movies?',
    'Would you rather explore space or the deep ocean?',
    'Would you rather always be ten minutes early or always be on time exactly?',
    'Would you rather have a pause button or a rewind button for life?',
    'Would you rather be able to talk to animals or speak every language?',
    'Would you rather live by the mountains or by the sea?',
    'Would you rather have a snowy winter all year or a sunny summer all year?',
    'Would you rather be a famous musician or a famous inventor?',
    'Would you rather travel to the past or the future?',
    'Would you rather have the power to heal or the power to fly?',
    'Would you rather always know the time or always know the way?',
    'Would you rather give up pizza or give up ice cream forever?',
    'Would you rather be the funniest person in the room or the smartest?',
    'Would you rather have a personal chef or a personal tour guide?',
    'Would you rather visit every country or master every musical instrument?',
    'Would you rather have a pet dragon or a pet unicorn?',
    'Would you rather always have great hair or always have comfy shoes?',
    'Would you rather be able to teleport or have super speed?',
    'Would you rather live in a treehouse or a houseboat?',
    'Would you rather be able to paint beautifully or sing beautifully?',
    'Would you rather have endless creativity or endless patience?',
    'Would you rather spend a day at a theme park or a day at the beach?',
    'Would you rather have a garden full of flowers or a garden full of vegetables?',
  ],
};

export const categoryLabels: Record<QuestionCategory, string> = {
  icebreakers: 'Ice-breakers',
  fun: 'Fun & random',
  deep: 'Deep & thoughtful',
  wouldYouRather: 'Would you rather',
};
