export type Region = 'Africa' | 'Asia' | 'Europe' | 'North America' | 'South America' | 'Oceania';

export interface Country {
  name: string;
  flag: string;
  capital: string;
  region: Region;
}

export const countries: Country[] = [
  // Africa
  { name: 'Algeria', flag: '🇩🇿', capital: 'Algiers', region: 'Africa' },
  { name: 'Egypt', flag: '🇪🇬', capital: 'Cairo', region: 'Africa' },
  { name: 'Ethiopia', flag: '🇪🇹', capital: 'Addis Ababa', region: 'Africa' },
  { name: 'Ghana', flag: '🇬🇭', capital: 'Accra', region: 'Africa' },
  { name: 'Kenya', flag: '🇰🇪', capital: 'Nairobi', region: 'Africa' },
  { name: 'Morocco', flag: '🇲🇦', capital: 'Rabat', region: 'Africa' },
  { name: 'Nigeria', flag: '🇳🇬', capital: 'Abuja', region: 'Africa' },
  { name: 'Senegal', flag: '🇸🇳', capital: 'Dakar', region: 'Africa' },
  { name: 'South Africa', flag: '🇿🇦', capital: 'Pretoria', region: 'Africa' },
  { name: 'Tanzania', flag: '🇹🇿', capital: 'Dodoma', region: 'Africa' },
  { name: 'Tunisia', flag: '🇹🇳', capital: 'Tunis', region: 'Africa' },
  { name: 'Uganda', flag: '🇺🇬', capital: 'Kampala', region: 'Africa' },
  { name: 'Zimbabwe', flag: '🇿🇼', capital: 'Harare', region: 'Africa' },
  { name: 'Cameroon', flag: '🇨🇲', capital: 'Yaoundé', region: 'Africa' },
  { name: 'Ivory Coast', flag: '🇨🇮', capital: 'Yamoussoukro', region: 'Africa' },
  { name: 'Madagascar', flag: '🇲🇬', capital: 'Antananarivo', region: 'Africa' },
  { name: 'Botswana', flag: '🇧🇼', capital: 'Gaborone', region: 'Africa' },
  { name: 'Namibia', flag: '🇳🇦', capital: 'Windhoek', region: 'Africa' },

  // Asia
  { name: 'China', flag: '🇨🇳', capital: 'Beijing', region: 'Asia' },
  { name: 'India', flag: '🇮🇳', capital: 'New Delhi', region: 'Asia' },
  { name: 'Indonesia', flag: '🇮🇩', capital: 'Jakarta', region: 'Asia' },
  { name: 'Japan', flag: '🇯🇵', capital: 'Tokyo', region: 'Asia' },
  { name: 'South Korea', flag: '🇰🇷', capital: 'Seoul', region: 'Asia' },
  { name: 'Malaysia', flag: '🇲🇾', capital: 'Kuala Lumpur', region: 'Asia' },
  { name: 'Pakistan', flag: '🇵🇰', capital: 'Islamabad', region: 'Asia' },
  { name: 'Philippines', flag: '🇵🇭', capital: 'Manila', region: 'Asia' },
  { name: 'Singapore', flag: '🇸🇬', capital: 'Singapore', region: 'Asia' },
  { name: 'Thailand', flag: '🇹🇭', capital: 'Bangkok', region: 'Asia' },
  { name: 'Vietnam', flag: '🇻🇳', capital: 'Hanoi', region: 'Asia' },
  { name: 'Saudi Arabia', flag: '🇸🇦', capital: 'Riyadh', region: 'Asia' },
  { name: 'United Arab Emirates', flag: '🇦🇪', capital: 'Abu Dhabi', region: 'Asia' },
  { name: 'Israel', flag: '🇮🇱', capital: 'Jerusalem', region: 'Asia' },
  { name: 'Turkey', flag: '🇹🇷', capital: 'Ankara', region: 'Asia' },
  { name: 'Iran', flag: '🇮🇷', capital: 'Tehran', region: 'Asia' },
  { name: 'Iraq', flag: '🇮🇶', capital: 'Baghdad', region: 'Asia' },
  { name: 'Bangladesh', flag: '🇧🇩', capital: 'Dhaka', region: 'Asia' },
  { name: 'Sri Lanka', flag: '🇱🇰', capital: 'Colombo', region: 'Asia' },
  { name: 'Nepal', flag: '🇳🇵', capital: 'Kathmandu', region: 'Asia' },
  { name: 'Kazakhstan', flag: '🇰🇿', capital: 'Astana', region: 'Asia' },
  { name: 'Jordan', flag: '🇯🇴', capital: 'Amman', region: 'Asia' },
  { name: 'Qatar', flag: '🇶🇦', capital: 'Doha', region: 'Asia' },

  // Europe
  { name: 'Austria', flag: '🇦🇹', capital: 'Vienna', region: 'Europe' },
  { name: 'Belgium', flag: '🇧🇪', capital: 'Brussels', region: 'Europe' },
  { name: 'Croatia', flag: '🇭🇷', capital: 'Zagreb', region: 'Europe' },
  { name: 'Czechia', flag: '🇨🇿', capital: 'Prague', region: 'Europe' },
  { name: 'Denmark', flag: '🇩🇰', capital: 'Copenhagen', region: 'Europe' },
  { name: 'Finland', flag: '🇫🇮', capital: 'Helsinki', region: 'Europe' },
  { name: 'France', flag: '🇫🇷', capital: 'Paris', region: 'Europe' },
  { name: 'Germany', flag: '🇩🇪', capital: 'Berlin', region: 'Europe' },
  { name: 'Greece', flag: '🇬🇷', capital: 'Athens', region: 'Europe' },
  { name: 'Hungary', flag: '🇭🇺', capital: 'Budapest', region: 'Europe' },
  { name: 'Iceland', flag: '🇮🇸', capital: 'Reykjavík', region: 'Europe' },
  { name: 'Ireland', flag: '🇮🇪', capital: 'Dublin', region: 'Europe' },
  { name: 'Italy', flag: '🇮🇹', capital: 'Rome', region: 'Europe' },
  { name: 'Netherlands', flag: '🇳🇱', capital: 'Amsterdam', region: 'Europe' },
  { name: 'Norway', flag: '🇳🇴', capital: 'Oslo', region: 'Europe' },
  { name: 'Poland', flag: '🇵🇱', capital: 'Warsaw', region: 'Europe' },
  { name: 'Portugal', flag: '🇵🇹', capital: 'Lisbon', region: 'Europe' },
  { name: 'Romania', flag: '🇷🇴', capital: 'Bucharest', region: 'Europe' },
  { name: 'Russia', flag: '🇷🇺', capital: 'Moscow', region: 'Europe' },
  { name: 'Spain', flag: '🇪🇸', capital: 'Madrid', region: 'Europe' },
  { name: 'Sweden', flag: '🇸🇪', capital: 'Stockholm', region: 'Europe' },
  { name: 'Switzerland', flag: '🇨🇭', capital: 'Bern', region: 'Europe' },
  { name: 'Ukraine', flag: '🇺🇦', capital: 'Kyiv', region: 'Europe' },
  { name: 'United Kingdom', flag: '🇬🇧', capital: 'London', region: 'Europe' },
  { name: 'Serbia', flag: '🇷🇸', capital: 'Belgrade', region: 'Europe' },
  { name: 'Bulgaria', flag: '🇧🇬', capital: 'Sofia', region: 'Europe' },

  // North America
  { name: 'Canada', flag: '🇨🇦', capital: 'Ottawa', region: 'North America' },
  { name: 'United States', flag: '🇺🇸', capital: 'Washington, D.C.', region: 'North America' },
  { name: 'Mexico', flag: '🇲🇽', capital: 'Mexico City', region: 'North America' },
  { name: 'Cuba', flag: '🇨🇺', capital: 'Havana', region: 'North America' },
  { name: 'Jamaica', flag: '🇯🇲', capital: 'Kingston', region: 'North America' },
  { name: 'Guatemala', flag: '🇬🇹', capital: 'Guatemala City', region: 'North America' },
  { name: 'Costa Rica', flag: '🇨🇷', capital: 'San José', region: 'North America' },
  { name: 'Panama', flag: '🇵🇦', capital: 'Panama City', region: 'North America' },
  { name: 'Honduras', flag: '🇭🇳', capital: 'Tegucigalpa', region: 'North America' },
  { name: 'Dominican Republic', flag: '🇩🇴', capital: 'Santo Domingo', region: 'North America' },
  { name: 'El Salvador', flag: '🇸🇻', capital: 'San Salvador', region: 'North America' },
  { name: 'Nicaragua', flag: '🇳🇮', capital: 'Managua', region: 'North America' },
  { name: 'Bahamas', flag: '🇧🇸', capital: 'Nassau', region: 'North America' },
  { name: 'Trinidad and Tobago', flag: '🇹🇹', capital: 'Port of Spain', region: 'North America' },

  // South America
  { name: 'Argentina', flag: '🇦🇷', capital: 'Buenos Aires', region: 'South America' },
  { name: 'Bolivia', flag: '🇧🇴', capital: 'Sucre', region: 'South America' },
  { name: 'Brazil', flag: '🇧🇷', capital: 'Brasília', region: 'South America' },
  { name: 'Chile', flag: '🇨🇱', capital: 'Santiago', region: 'South America' },
  { name: 'Colombia', flag: '🇨🇴', capital: 'Bogotá', region: 'South America' },
  { name: 'Ecuador', flag: '🇪🇨', capital: 'Quito', region: 'South America' },
  { name: 'Paraguay', flag: '🇵🇾', capital: 'Asunción', region: 'South America' },
  { name: 'Peru', flag: '🇵🇪', capital: 'Lima', region: 'South America' },
  { name: 'Uruguay', flag: '🇺🇾', capital: 'Montevideo', region: 'South America' },
  { name: 'Venezuela', flag: '🇻🇪', capital: 'Caracas', region: 'South America' },
  { name: 'Guyana', flag: '🇬🇾', capital: 'Georgetown', region: 'South America' },
  { name: 'Suriname', flag: '🇸🇷', capital: 'Paramaribo', region: 'South America' },

  // Oceania
  { name: 'Australia', flag: '🇦🇺', capital: 'Canberra', region: 'Oceania' },
  { name: 'New Zealand', flag: '🇳🇿', capital: 'Wellington', region: 'Oceania' },
  { name: 'Fiji', flag: '🇫🇯', capital: 'Suva', region: 'Oceania' },
  { name: 'Papua New Guinea', flag: '🇵🇬', capital: 'Port Moresby', region: 'Oceania' },
  { name: 'Samoa', flag: '🇼🇸', capital: 'Apia', region: 'Oceania' },
  { name: 'Tonga', flag: '🇹🇴', capital: "Nuku'alofa", region: 'Oceania' },
  { name: 'Vanuatu', flag: '🇻🇺', capital: 'Port Vila', region: 'Oceania' },
  { name: 'Solomon Islands', flag: '🇸🇧', capital: 'Honiara', region: 'Oceania' },
];
