export const bibleThemes = [
  'Encouragement',
  'Eternal Life',
  'Faith',
  'Family and Marriage',
  'Forgiveness',
  "God's Guidance",
  "God's Justice",
  "God's Mercy",
  "God's Promises",
  "God's Protection",
  'Grace',
  'Healing',
  'Hope',
  'Humility',
  'Joy',
  'Love',
  'Obedience',
  'Overcoming Fear',
  'Patience',
  'Peace',
  'Perseverance',
  'Prayer',
  'Repentance',
  'Salvation',
  'Serving Others',
  'Spiritual Warfare',
  'Strength',
  'Thankfulness',
  'Trust in God',
  'Wisdom'
]; 