export type Difficulty = 'easy' | 'medium' | 'bold';

export const truths: Record<Difficulty, string[]> = {
  easy: [
    'What is your all-time favorite movie?',
    'What is your favorite food to eat for breakfast?',
    'What was your favorite subject in school?',
    'What is one hobby you could do for hours?',
    'Who is your favorite cartoon character?',
    'What is the best gift you have ever received?',
    'What is your favorite season of the year and why?',
    'What is a song you can never get tired of?',
    'What is your favorite thing to do on a weekend?',
    'If you could have any pet, what would it be?',
    'What is your favorite holiday and why?',
    'What is the best book you have ever read?',
    'What is your go-to comfort snack?',
    'What is your favorite board game or video game?',
    'What is one place you would love to visit someday?',
    'What is your favorite ice cream flavor?',
    'Who is someone you really look up to?',
    'What is your favorite way to spend a rainy day?',
    'What is the best meal you can cook?',
    'What is your favorite animal at the zoo?',
  ],
  medium: [
    'What is the most embarrassing thing that happened to you at school?',
    'What is a talent most people do not know you have?',
    'What is the silliest thing you are afraid of?',
    'What is the weirdest food combination you secretly enjoy?',
    'What is a small habit you have that annoys other people?',
    'What is the last thing you searched for on your phone?',
    'What is the biggest lie you told to get out of something?',
    'What is your most-used emoji and why?',
    'What is the worst haircut you have ever had?',
    'What is something you pretend to like but actually do not?',
    'What is the most childish thing you still do?',
    'What is a song you are embarrassed to admit you love?',
    'What is the strangest dream you can remember having?',
    'What is the most useless thing you know how to do?',
    'What is something you have never told your best friend?',
    'What is the worst gift you have ever given someone?',
    'What is a fear you had as a kid that you have now outgrown?',
    'What is the most trouble you ever got into at home?',
    'What chore do you avoid doing as long as possible?',
    'What is the cringiest thing in your search or text history?',
  ],
  bold: [
    'What is the most spontaneous thing you have ever done?',
    'What is a goal you have never told anyone about?',
    'What is the most embarrassing thing in your room right now?',
    'If you could swap lives with anyone here for a day, who would it be?',
    'What is the biggest risk you have ever taken?',
    'What is something you really want to do but are too nervous to try?',
    'What is the most rebellious thing you have ever done?',
    'What is a secret talent you would show off if you had to perform right now?',
    'What is the wildest thing on your bucket list?',
    'What is the most over-the-top reaction you have ever had to good news?',
    'What is something you would do if you knew you could not fail?',
    'What is the boldest fashion choice you have ever made?',
    'What is the most dramatic thing you have ever done to win an argument?',
    'What is a rule you love to break when no one is looking?',
    'What is the most adventurous food you have ever tried?',
    'What is something you have always wanted to confess to the group?',
    'What is the cheesiest pickup line you actually think is funny?',
    'What is the most competitive you have ever gotten over something small?',
    'What is the strangest thing you have ever done when you thought you were alone?',
    'If you had to give a TED talk tomorrow, what would it be about?',
  ],
};

export const dares: Record<Difficulty, string[]> = {
  easy: [
    'Do your best impression of a barnyard animal.',
    'Talk in a robot voice until your next turn.',
    'Give everyone in the room a high five.',
    'Hop on one foot for fifteen seconds.',
    'Say the alphabet backwards as fast as you can.',
    'Do ten jumping jacks right now.',
    'Make up a short jingle about your favorite snack.',
    'Pretend to be a news anchor and report the weather.',
    'Do your best slow-motion walk across the room.',
    'Smile without showing your teeth for thirty seconds.',
    'Balance a small object on your head for ten seconds.',
    'Speak in a whisper until your next turn.',
    'Do your best impression of a famous cartoon laugh.',
    'Pretend to be a tour guide showing off the room.',
    'Wave at an imaginary crowd like a celebrity.',
    'Do your best superhero pose and hold it for ten seconds.',
    'Make the silliest face you can and hold it for five seconds.',
    'Pretend to be a statue until someone counts to ten.',
    'Do your best impression of a clucking chicken.',
    'Give a dramatic introduction for the next player.',
  ],
  medium: [
    'Do your best impression of a celebrity until someone guesses who it is.',
    'Sing the chorus of any song out loud.',
    'Talk in an accent of your choice until your next turn.',
    'Do your best runway model walk across the room.',
    'Act out your favorite movie scene without saying the title.',
    'Do an impression of someone else in the room.',
    'Dance with no music for twenty seconds.',
    'Tell a joke and keep trying until someone laughs.',
    'Speak only in questions until your next turn.',
    'Do your best impression of a sports commentator narrating the room.',
    'Pretend to host a cooking show using whatever is nearby.',
    'Make up a two-line poem about the person to your left.',
    'Do your best dramatic movie villain laugh.',
    'Act like your favorite animal until your next turn.',
    'Do a cartwheel or your best attempt at one.',
    'Pretend you are a superhero and explain your powers.',
    'Do your best impression of a baby learning to walk.',
    'Give a thirty-second motivational speech about doing chores.',
    'Sing your next three sentences like an opera singer.',
    'Do your best invisible jump-rope routine.',
  ],
  bold: [
    'Do a dramatic interpretive dance to a song the group picks.',
    'Let the group give you a silly nickname for the rest of the game.',
    'Do your best impression of each player one after another.',
    'Perform a one-minute stand-up comedy set on the spot.',
    'Act out an entire fairy tale by yourself in thirty seconds.',
    'Let the person to your right pose you like a mannequin and hold it.',
    'Sing a whole verse and chorus of a song while standing on a chair.',
    'Do your best dramatic crying scene as if you just lost an award.',
    'Make up a commercial for a random object in the room and perform it.',
    'Do your best catwalk strut and a dramatic pose at the end.',
    'Give a passionate award acceptance speech thanking the whole group.',
    'Reenact your most embarrassing moment as a silent movie.',
    'Let the group choose a dance move you must do every turn for the rest of the game.',
    'Do an impression of a teacher giving a very serious lesson about nothing.',
    'Perform your favorite song using only humming and air instruments.',
    'Do your best impression of a robot malfunctioning.',
    'Act out three different emotions in ten seconds while the group guesses.',
    'Pretend to be a fortune teller and predict each player’s next 24 hours.',
    'Do your best wrestling entrance complete with a catchphrase.',
    'Narrate everything you do in third person until your next turn.',
  ],
};
