export type WyrCategory = 'classic' | 'funny' | 'hard' | 'food' | 'gross' | 'deep' | 'kids';

export const categoryLabels: Record<WyrCategory, string> = {
  classic: 'Classic',
  funny: 'Funny',
  hard: 'Hard / impossible',
  food: 'Food',
  gross: 'Gross',
  deep: 'Deep',
  kids: 'For kids',
};

export const dilemmas: Record<WyrCategory, string[]> = {
  classic: [
    'Would you rather be able to fly or be invisible?',
    'Would you rather be the funniest person in the room or the smartest?',
    'Would you rather always be 10 minutes late or 20 minutes early?',
    'Would you rather live in the city or the countryside?',
    'Would you rather have unlimited money or unlimited time?',
    'Would you rather be famous or be the best friend of someone famous?',
    'Would you rather never have to sleep or never have to eat?',
    'Would you rather travel to the past or the future?',
    'Would you rather have more time or more money?',
    'Would you rather be able to teleport anywhere or read minds?',
    'Would you rather live without music or without movies?',
    'Would you rather always know when someone is lying or always get away with lying?',
    'Would you rather be a master of every instrument or speak every language?',
    'Would you rather give up your phone for a month or your bed for a month?',
    'Would you rather have a rewind button or a pause button for your life?',
  ],
  funny: [
    'Would you rather fight one horse-sized duck or a hundred duck-sized horses?',
    'Would you rather have spaghetti for hair or sweat maple syrup?',
    'Would you rather sneeze glitter or burp bubbles for the rest of your life?',
    'Would you rather always have to skip instead of walk or sing instead of talk?',
    'Would you rather have a permanent clown face or permanent clown shoes?',
    'Would you rather speak only in rhymes or only in questions?',
    'Would you rather have fingers as long as your legs or legs as long as your fingers?',
    'Would you rather be unable to whisper or unable to speak quietly?',
    'Would you rather fart every time you laugh or hiccup every time you talk?',
    'Would you rather have a tail you cannot control or wings you cannot use?',
    'Would you rather always smell like a wet dog or always look like you just woke up?',
    'Would you rather have Wi-Fi everywhere you go but it is always slow, or fast Wi-Fi only at home?',
    'Would you rather wear shoes on the wrong feet forever or wear your clothes inside out forever?',
    'Would you rather have a personal theme song that plays when you enter a room or subtitles under you at all times?',
  ],
  hard: [
    'Would you rather lose all your old memories or never be able to make new ones?',
    'Would you rather be feared by everyone or forgotten by everyone?',
    'Would you rather save 100 strangers or one person you love?',
    'Would you rather know how you will die or when you will die?',
    'Would you rather be able to end all war or end all disease, but only one?',
    'Would you rather give up the internet for a year or air conditioning and heating for a year?',
    'Would you rather always tell the truth or always have to lie?',
    'Would you rather relive the same day for a year or lose a year of your life?',
    'Would you rather be the most talented person who never gets recognized or famous for something you did not do?',
    'Would you rather have a "do-over" button or a "fast-forward" button, but you can only use it once?',
    'Would you rather be stuck on a deserted island alone or with someone you cannot stand?',
    'Would you rather lose the ability to read or the ability to speak?',
  ],
  food: [
    'Would you rather give up cheese or give up chocolate forever?',
    'Would you rather only eat sweet food or only eat savory food?',
    'Would you rather have unlimited pizza or unlimited tacos for life?',
    'Would you rather never drink coffee again or never drink soda again?',
    'Would you rather eat your favorite meal every day or never eat the same meal twice?',
    'Would you rather have a kitchen that cooks for you or a fridge that never runs out?',
    'Would you rather only eat foods that are spicy or only eat foods that are bland?',
    'Would you rather give up bread or give up pasta?',
    'Would you rather eat a whole raw onion or a whole raw lemon?',
    'Would you rather have breakfast foods only or dinner foods only for the rest of your life?',
    'Would you rather drink everything through a straw or eat everything with a spoon?',
  ],
  gross: [
    'Would you rather eat a worm or a grasshopper?',
    'Would you rather drink a glass of spoiled milk or a glass of pickle juice?',
    'Would you rather smell rotten eggs all day or hear nails on a chalkboard all day?',
    'Would you rather lick a public door handle or a shopping cart handle?',
    'Would you rather have permanent bad breath or permanently sweaty hands?',
    'Would you rather step on a slug barefoot or get a paper cut between your fingers?',
    'Would you rather have a booger you can never pick or an itch you can never scratch?',
    'Would you rather eat a sandwich made by your worst enemy or one you found on the floor?',
    'Would you rather brush your teeth with soap or wash your hair with mustard?',
  ],
  deep: [
    'Would you rather be deeply loved or deeply respected?',
    'Would you rather have a job you love that pays little or a job you hate that pays a lot?',
    'Would you rather find true love or your true purpose in life?',
    'Would you rather be content with what you have or always striving for more?',
    'Would you rather change one decision from your past or see one moment of your future?',
    'Would you rather be remembered for one great thing or loved by a few people who really knew you?',
    'Would you rather have the power to heal others or the power to understand anyone?',
    'Would you rather always say what you feel or always keep the peace?',
    'Would you rather know everyone’s true opinion of you or never think about it again?',
    'Would you rather have fewer, deeper friendships or many casual ones?',
  ],
  kids: [
    'Would you rather have a pet dragon or a pet unicorn?',
    'Would you rather be a superhero or a wizard?',
    'Would you rather eat ice cream for breakfast or pizza for breakfast?',
    'Would you rather be able to talk to animals or talk to plants?',
    'Would you rather have a treehouse or a secret underground hideout?',
    'Would you rather be the size of a mouse or as tall as a giraffe?',
    'Would you rather swim like a fish or run as fast as a cheetah?',
    'Would you rather have summer all year or snow all year?',
    'Would you rather build the biggest sandcastle or the tallest snowman?',
    'Would you rather have a magic backpack that holds anything or shoes that let you jump super high?',
    'Would you rather visit the moon or the bottom of the ocean?',
    'Would you rather have a robot best friend or a talking pet?',
  ],
};
